### ISSUE TITLE
Active cooling - FAN

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#17]
Some preparation, if we really need active cooling:

Supply for fan is 3.3 V.
Fan is controlled with N-mosfet.

Control voltage must be over about 1.5V for mosfet to turn ON and pass more than enough current
Control is done by FPGA (pin E4)  or LM75 open drain output (0R resistor not placed)
LM75 has an  open drain output LM75 OS which is pulled-up by an external 10k R
OS Polaritiy can be set to active high or active low. If directly connected to mosfet setting must be active high.

Retail available fans of size 30 and 40 mm come with conn pitch 2.54 so a 2-pin male header must be additionally soldered
![image](https://cloud.githubusercontent.com/assets/1379063/21582477/694ad0dc-d059-11e6-9c53-ccad84420ba9.png)

Most retail fans come for voltages 5, 12 and 24V so 5V fan with 3.3V supply must be checked
Example fans 5V in 1pcs QTY with shipping
30x30x7: http://www.ebay.com/itm/301966472303  1.5$
40x40x7: http://www.ebay.com/itm/400965990547   2.5$
40x40x10: http://www.ebay.com/itm/222325450566 1.5$
40x40x10: http://www.ebay.com/itm/252478255390 1.5$

Clearance for fan and heatsink in 4 io enclosure will matter

Datasheets:
https://www.fairchildsemi.com/datasheets/ND/NDS331N.pdf
http://datasheets.maximintegrated.com/en/ds/LM75.pdf

Shematics from: https://github.com/myriadrf/LimeSDR-USB/blob/master/hardware/plug/1v4/Project%20Outputs%20for%20LimeSDR-USB_1v4_LMS031pad/LimeSDR-USB_1v4_schematic_r7.PDF

**Comment by lleoha** [comment]
👍 
Active cooling would be great, as my Lime is overheating unfortunately.
@luftek Did you consider using small 17x17x5  3.3V DC fan like this one:
http://www.digikey.com/en/product-highlight/c/copal/f17fa-03mc-mini-brushless-dc-fan
or even smaller one (15x15x4.5 but this one is 5V  DC):
http://www.ebay.com/itm/15x15mm-Super-Small-Brushless-DC-Fan-Ultra-Tiny-Miniature-Mini-Micro-Smallest-/181152651845

I would prefer to have it as small as possible to fit it on the PCB panel instead of metal case itself (I think is would be easier for me - I don't have tools to make good looking holes in metal case) and (if needed) put some radiators on chips.

Let me know what you think.. If there is anything I can help you with let me know.
Thanks!

**Comment by zigastegu** [comment]
I didn't know, so small fans exist :) Friend milled aluminum cutouts for me and are at postal office. i go pick them up tomorrow. will update this comment.

Currently I know of 2 temperatures that can be read.
1. dedicated chip - LM75, LimeSuite supports it
2. internal LMS temperature, LimeSuite does has this functionality but does not work correctly in my version (maybe need update)

How do you do temperature testing, reading?

**Comment by lleoha** [comment]
I was using pyrometer and the chip temperature was ca. ~80*C

**Comment by luftek** [comment]
some progress with KIT, which is avaiable on eBay. Instructions and BOM.csv follows shortly
http://www.ebay.com/itm/-/122582037877?

**Comment by zigastegu** [comment]
Fan used in version 1v0
Commit: dc9700f
Kit sold on eBay: http://www.ebay.com/itm/-/122582037877
