### ISSUE TITLE
is DC socket populated on the board?

### ISSUE THREAD

**Issue by zigastegu** [luftek/LimeSDR-USB#4]
It this is not the case:
- I need to make a hole plug for DC plug also OR
- put suitable 3.5 mm DC socket in BOM.xlsx

**Comment by m3us** [comment]
Hey Luftek,I think it will be populated since its mentioned in the BOM here 

https://github.com/myriadrf/LimeSDR-USB/blob/master/hardware/plug/1v2/Project%20Outputs%20for%20LimeSDR_1v2/BOM/LimeSDR_1v2_BOMr1.xls

![image](https://cloud.githubusercontent.com/assets/6883277/18052625/7c0f05d0-6e0c-11e6-8ce0-a995f4bad3a2.png)

**Comment by zigastegu** [comment]
Yes, probably true. Just saw some prototype boards without.
added to BOM with a comment
